-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- Drop table

-- DROP TABLE public.appointments;

CREATE TABLE public.appointments (
	id bigserial NOT NULL,
	doctor_id int8 NOT NULL,
	patient_id int8 NOT NULL,
	datetime timestamp NOT NULL,
	status varchar(255) NOT NULL,
	qr_code_url varchar(255) NULL,
	CONSTRAINT appointments_pkey PRIMARY KEY (id),
	CONSTRAINT uk_doctor_patient_datetime UNIQUE (doctor_id, patient_id, datetime),
	CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctor(id) ON DELETE CASCADE,
	CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- Tabla de logs de auditoría
CREATE TABLE IF NOT EXISTS public.audit_logs (
	id bigserial PRIMARY KEY,
	user_name varchar(255) NOT NULL,
	action varchar(255) NOT NULL,
	details text,
	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Drop table

-- DROP TABLE public.doctor;

CREATE TABLE public.doctor (
	id int8 NOT NULL,
	especialidad varchar(255) NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT doctor_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.patients;

CREATE TABLE public.patients (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	apellido varchar(255) NULL,
	dni varchar(255) NULL,
	email varchar(255) NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT patients_pkey PRIMARY KEY (id),
	CONSTRAINT ukkwg4jhsdnxhullscn35csrnce UNIQUE (dni)
);

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NOT NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	password_hash varchar(255) NOT NULL,
	"role" varchar(255) NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'DOCTOR'::character varying, 'PACIENTE'::character varying])::text[])))
);